# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1287, 757)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = PlotWidget(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 1261, 371))
        self.graphicsView.setObjectName("graphicsView")
        self.listGesture = QtWidgets.QListWidget(self.centralwidget)
        self.listGesture.setGeometry(QtCore.QRect(280, 530, 221, 161))
        self.listGesture.setObjectName("listGesture")
        self.btnStop = QtWidgets.QPushButton(self.centralwidget)
        self.btnStop.setGeometry(QtCore.QRect(280, 430, 211, 31))
        self.btnStop.setObjectName("btnStop")
        self.cbComPort = QtWidgets.QComboBox(self.centralwidget)
        self.cbComPort.setGeometry(QtCore.QRect(60, 391, 171, 22))
        self.cbComPort.setObjectName("cbComPort")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(910, 400, 361, 321))
        self.groupBox.setObjectName("groupBox")
        self.imageTraining = QtWidgets.QLabel(self.groupBox)
        self.imageTraining.setGeometry(QtCore.QRect(10, 20, 351, 291))
        self.imageTraining.setText("")
        self.imageTraining.setObjectName("imageTraining")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(530, 400, 371, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.imageTesting = QtWidgets.QLabel(self.groupBox_2)
        self.imageTesting.setGeometry(QtCore.QRect(10, 20, 351, 291))
        self.imageTesting.setText("")
        self.imageTesting.setObjectName("imageTesting")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 393, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cbBaudRate = QtWidgets.QComboBox(self.centralwidget)
        self.cbBaudRate.setGeometry(QtCore.QRect(109, 439, 121, 22))
        self.cbBaudRate.setObjectName("cbBaudRate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 440, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(280, 390, 211, 31))
        self.btnStart.setObjectName("btnStart")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 490, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnTraining = QtWidgets.QPushButton(self.centralwidget)
        self.btnTraining.setGeometry(QtCore.QRect(140, 630, 121, 51))
        self.btnTraining.setObjectName("btnTraining")
        self.btnTesting = QtWidgets.QPushButton(self.centralwidget)
        self.btnTesting.setGeometry(QtCore.QRect(10, 630, 121, 51))
        self.btnTesting.setObjectName("btnTesting")
        self.txtGestureInput = QtWidgets.QLineEdit(self.centralwidget)
        self.txtGestureInput.setGeometry(QtCore.QRect(370, 486, 131, 31))
        self.txtGestureInput.setObjectName("txtGestureInput")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(280, 700, 101, 31))
        self.btnAdd.setObjectName("btnAdd")
        self.btnRemove = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemove.setGeometry(QtCore.QRect(400, 700, 101, 31))
        self.btnRemove.setObjectName("btnRemove")
        self.labelPrediction = QtWidgets.QLabel(self.centralwidget)
        self.labelPrediction.setGeometry(QtCore.QRect(10, 680, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.labelPrediction.setFont(font)
        self.labelPrediction.setStyleSheet("color: red")
        self.labelPrediction.setAutoFillBackground(False)
        self.labelPrediction.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPrediction.setObjectName("labelPrediction")
        self.cbApplications = QtWidgets.QComboBox(self.centralwidget)
        self.cbApplications.setGeometry(QtCore.QRect(101, 490, 91, 22))
        self.cbApplications.setObjectName("cbApplications")
        self.btnEnter = QtWidgets.QPushButton(self.centralwidget)
        self.btnEnter.setGeometry(QtCore.QRect(200, 490, 61, 23))
        self.btnEnter.setObjectName("btnEnter")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(9, 490, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 530, 251, 91))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 47, 13))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.btnUpLeft = QtWidgets.QPushButton(self.groupBox_3)
        self.btnUpLeft.setGeometry(QtCore.QRect(10, 30, 111, 41))
        self.btnUpLeft.setObjectName("btnUpLeft")
        self.btnBottomRight = QtWidgets.QPushButton(self.groupBox_3)
        self.btnBottomRight.setGeometry(QtCore.QRect(130, 30, 111, 41))
        self.btnBottomRight.setObjectName("btnBottomRight")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.groupBox.setTitle(_translate("MainWindow", "Training Plot"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Testing Plot"))
        self.label.setText(_translate("MainWindow", "COM:"))
        self.label_2.setText(_translate("MainWindow", "BAUDRATE:"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.label_3.setText(_translate("MainWindow", "Gestures list"))
        self.btnTraining.setText(_translate("MainWindow", "Record Training Data"))
        self.btnTesting.setText(_translate("MainWindow", "Record Testing Data"))
        self.btnAdd.setText(_translate("MainWindow", "Add"))
        self.btnRemove.setText(_translate("MainWindow", "Remove"))
        self.labelPrediction.setText(_translate("MainWindow", "unknown gesture"))
        self.btnEnter.setText(_translate("MainWindow", "Enter"))
        self.label_4.setText(_translate("MainWindow", "Application:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Calibration"))
        self.btnUpLeft.setText(_translate("MainWindow", "Up Left"))
        self.btnBottomRight.setText(_translate("MainWindow", "Bottom Right"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
